### ISSUE TITLE
game crashed with s&r 1.4.2

### ISSUE THREAD

**Issue by Quinnie333** [Layers-of-Railways/Railway#171]
i got this crash report when i tried to open my game with the mod updated 
Several mod has failed to load such as 
modern fix
architectury
better animations collection
REI
create : central kitchen
diagonal fences
puzzles lib

[crash-2023-07-07_09.13.50-fml.txt](https://github.com/Layers-of-Railways/Railway/files/11977335/crash-2023-07-07_09.13.50-fml.txt)

**Comment by SpottyTheTurtle** [comment]
Remove modernfix

**Comment by embeddedt** [comment]
This issue is caused by Steam n Rails adding a mixin into the recipe manager to suppress the same error that ModernFix already suppresses the stack trace from for all mods. The next version of ModernFix has been improved to not crash when other mods make a change like this. It can also be worked around by disabling that option (datapack_reload_exceptions) in the config, there is absolutely no need to remove the whole mod.

**Comment by SpottyTheTurtle** [comment]
didn't know modernfix had been updated to include a fix to that issue

**Comment by embeddedt** [comment]
The update is not out yet but the workaround can be used immediately.
