### ISSUE TITLE
1.18.2 Forge "spongemixin" crash.

### ISSUE THREAD

**Issue by TheDoctor1977** [Layers-of-Railways/Railway#28]
Crashlog: https://mclo.gs/svJEhAl

No idea what caused this. Removing the mod stops the crash, so it's definitely this one causing it.

**Comment by techno-sam** [comment]
`Caused by: org.spongepowered.asm.mixin.throwables.ClassMetadataNotFoundException: com.tterrag.registrate.util.entry.BlockEntry`

I don't know why it wouldn't know about registrate. If you can send your mods in a zip, that would be helpful.

**Comment by techno-sam** [comment]
Oh, maybe optifine is the problem. does it work fine with this mod, but without optifine?

**Comment by PixlePizza** [comment]
I am having the same issue but I don't have optifine installed at all.

**Comment by TheDoctor1977** [comment]
> Oh, maybe optifine is the problem. does it work fine with this mod, but without optifine?

Not using optifine. There's a lot of them so the zip is too large for github, here's a drive link. https://drive.google.com/drive/folders/1S6fRHt3NnItqA5S0RsV5BDgD2ueTybtM?usp=share_link

Edit: I should note that S&R is removed from this, but I was using version 1.03.

**Comment by MinerMinerMods** [comment]
Same problem with create(KubeJS, PonderJS, Steam rails and (stuff and additions)), KubeJS(Create and Ponder addons), clumps, lazy DFU
the downloaded [mods](https://github.com/Layers-of-Railways/Railway/files/10272942/mods.zip), also the error code was 255. By doing light reading I believe the mod is improperly configured due to these logs: 

> org.spongepowered.asm.mixin.throwables.MixinApplyError: Mixin [mixins.railways.json:MixinReplaceTrackCheck] from phase [DEFAULT] in config [mixins.railways.json] FAILED during APPLY
> Caused by: org.spongepowered.asm.mixin.throwables.MixinApplyError: Mixin [mixins.railways.json:MixinReplaceTrackCheck] from phase [DEFAULT] in config [mixins.railways.json] FAILED during APPLY

[Full Log](https://github.com/Layers-of-Railways/Railway/files/10273539/ErrorLog.txt)

List of items to check;
- [ ] final mod .jar file
- [ ] error log(above)
- [ ] mixins setup

**Comment by MinerMinerMods** [comment]
pushed the issue to discord so it should be noticed

**Comment by techno-sam** [comment]
Yes `Caused by: org.spongepowered.asm.mixin.throwables.ClassMetadataNotFoundException: com.tterrag.registrate.util.entry.BlockEntry` not sure why this is happening

**Comment by techno-sam** [comment]
Oh wait. You are using Create 0.5.0c, you should be using Create 0.5.0e
