### ISSUE TITLE
STEAM N RAILS IS NOT WORKING WITH OPTIFINE

### ISSUE THREAD

**Issue by TUF-SCAR** [Layers-of-Railways/Railway#409]
### Describe the Bug

Steam n rails is not working with OPTIFINE please fix it 🥺🥺🥺

### Reproduction Steps

Launch steam n rails together with optifine

### Expected Result

Steam n rails to work with optifine 

### Operating System

Windows 10 Pro 

### Mod Version

1.5.3

### Create Mod Version

0.5.1f

### Minecraft Version

1.20.1

### ModLoader and Version

Forge 47.2.21

**Comment by samuelh2005** [comment]
Optifine is known to break mods. In addition Optifine is closed source which makes it impossible to diagnose problems caused by Optifine. As a result, many mods do not work with Optifine and many people recommend using alternatives.

If you want to use Fabric then Sodium is a better choice, or use the Forge port Embeddium.

**Comment by IThundxr** [comment]
Also fixed in next update already, the warning screen will be removed in 1.6.0 and it will be compatible again on 1.19.2
