### ISSUE TITLE
Mixin error on loading world

### ISSUE THREAD

**Issue by tmvkrpxl0** [Layers-of-Railways/Railway#471]
### Describe the Bug

When I join the world, error like this is shown in the log
https://hastebin.com/share/deliyegefi.bash

Here, create tried to load class `TrackPlacement` but something went wrong.
However, it's different class every time. I think it was previously something about TrackOverlay.

### Reproduction Steps

1. Install Railway
2. Install Create
3. Join world
4. See this error in log

### Expected Result

I expected there'd be no error.

### Operating System

KDE Neon 6.0 (Based on Ubuntu 22.04)

### Mod Version

1.6.3

### Create Mod Version

0.5.1f

### Minecraft Version

1.20.1

### ModLoader and Version

Forge 47.2.30

**Comment by Stradinius** [comment]
I am notably having this same issue within the Fabric version.  I can either make another post, or tack onto this one, but wanted to ask preference first.  It's also notably heavily modded otherwise, and I can't see the previous log post, but mine is referencing 

`Java.lang.BootstrapMethodError: java.lang.RuntimeException: Mixin transformation of com.simibubi.create.content.trains.entity.Train failed`=`

**Comment by IThundxr** [comment]
please use something like https://mclo.gs, the log seems to have expired

**Comment by tmvkrpxl0** [comment]
https://mclo.gs/mL9mvtL
Here. This is my debug.log.
I also installed mixin booster in case that'll help with logs. It was not related with the issue itself as same error happens with or without it.

**Comment by IThundxr** [comment]
that log doesn't show a crash, send the crash report through mclogs

**Comment by tmvkrpxl0** [comment]
Sorry, I should've clarified that it doesn't crash, I reported the issue as the error is always thrown.

**Comment by IThundxr** [comment]
if it doesn't crash you can ignore it, it's fine
